
name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  detect-changes:
    outputs:
      src: ${{ steps.filter.outputs.src }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: .github/file-filters.yml

  lint:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.src == 'true' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: golangci/golangci-lint-action@v2
      with:
        args: --config ./.golangci.yml
        working-directory: internal

  code-ql:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.src == 'true'}}
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
    - uses: actions/checkout@v2
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: 'go'
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1

  unit-test:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.src == 'true' }}
    runs-on: ubuntu-latest
    container: golang:latest
    steps:
    - uses: actions/checkout@v2
    - name: run unit tests and code coverage
      run: sh ./scripts/unit-test.sh

  build:
    needs: [ lint, code-ql, unit-test ]
    runs-on: ubuntu-latest
    container: golang:latest
    steps:
    - uses: actions/checkout@v2
    - name: build binary
      run: sh ./scripts/build.sh
